layout_spectrum: 0.9415812
typography_spectrum: 0.9871723
color:
  saturation: 0.6071072
  lightness: 0.1483468
  brandStrength: 0.9617661
  rhythmicContrast: 0.4858818
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
name: Jana Booker Studios
